# Copyright (C) 2017 Quentin "Naccyde" Deslandes.
# Redistribution and use of this file is allowed according to the terms of the MIT license.
# For details see the LICENSE file distributed with yall.

#
# Appveyor configuration
#
# Build the project on Visual Studio 2015, in debug and release mode, 64 bits.
#
# CMake flags :
#   * PROJECT_CI_DEPLOY : enable install inside the build directory
#
# Once a tag is pushed, the release build will be packed and push to GitHub.
#

version: '{branch}-{build}'

clone_folder: C:\yall

# Do not build when a tag is deployed
skip_tags: true

# Build only on master
branches:
  only:
    - master

environment:
    DEPLOY: 0
    TAG: 0
    matrix:
        - image: Visual Studio 2015
          platform: x64
          generator: "Visual Studio 14 2015 Win64"
        - image: Visual Studio 2015
          platform: x64
          generator: "Visual Studio 12 2013 Win64"

# Run CMake generation and define if the current build should be released.
# As build is done only on PR and on master, if this is not a PR, it should
# be released.
before_build:
    - ps: cd C:\yall
    - ps: cmake -G"%generator%"
    - ps: |
        if (-not (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER))
        {
            $env:DEPLOY=1
            $env:TAG = [IO.File]::ReadAllText("C:\yall\yall.version")
        }

build_script:
    - ps: cmake --build . --config Release --target ALL_BUILD

after_build:
    - ps: cmake --build . --config Release --target package
    - ps: cmake --build . --config Debug --target package

test_script:
    - cmd: if "%generator%" NEQ "Visual Studio 12 2013 Win64" cmake --build . --target unit
    
artifacts:
    - path: 'yall-*.zip'
      name: yall_zip

deploy:
    tag: $(TAG)
    provider: GitHub
    artifact: yall_zip
    auth_token:
        secure: ZWCkNHmbrBurrU0WLBESAeFdNkhuUsae1TApe8LR/cakzx5Puw/akJZBC3uaISnw
    draft: false
    on:
        DEPLOY: 1
