# Copyright (C) 2017 Quentin "Naccyde" Deslandes.
# Redistribution and use of this file is allowed according to the terms of the MIT license.
# For details see the LICENSE file distributed with yall.

#
# Appveyor configuration
#
# Build the project on Visual Studio 2015, in debug and release mode, 64 bits.
#
# CMake flags :
#   * PROJECT_CI_DEPLOY : enable install inside the build directory
#
# Once a tag is pushed, the release build will be packed and push to GitHub.
#

version: '{branch}-{build}'

clone_folder: C:\yall

branches:
  only:
    - master

environment:
    matrix:
        - image: Visual Studio 2015
          configuration: Release
          platform: x64
          generator: "Visual Studio 14 2015 Win64"
        - image: Visual Studio 2015
          configuration: Release
          platform: x64
          generator: "Visual Studio 12 2013 Win64"

before_build:
    - ps: if ($env.APPVEYOR_REPO_BRANCH -eq 'master') { $env.APPVEYOR_REPO_TAG = true }
#    - ps: if "%APPVEYOR_REPO_BRANCH%" == "master" (set /p APPVEYOR_REPO_TAG_NAME=<yall.version)
    - ps: echo $env:APPVEYOR_REPO_TAG
 #   - echo %APPVEYOR_REPO_TAG_NAME%
    - cd c:\yall
    - cmake -G"%generator%"

build_script:
    - cmd: cmake --build . --config %configuration% --target ALL_BUILD

test_script:
    - cmd: if "%generator%" NEQ "Visual Studio 12 2013 Win64" cmake --build . --target unit

before_deploy:
    - cmake --build . --config Release --target package
    - cmake --build . --config Debug --target package

artifacts:
    - path: 'yall-*.zip'
      name: yall_pack

deploy:
    release: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub
    artifact: yall_pack
    auth_token:
        secure: ZWCkNHmbrBurrU0WLBESAeFdNkhuUsae1TApe8LR/cakzx5Puw/akJZBC3uaISnw
    draft: false
    on:
        appveyor_repo_tag: true
