# Copyright (C) 2017 Quentin "Naccyde" Deslandes.
# Redistribution and use of this file is allowed according to the terms of the MIT license.
# For details see the LICENSE file distributed with yall.

#
# Appveyor configuration
#
# Build the project on Visual Studio 2015, in debug and release mode, 64 bits.
#
# CMake flags :
#   * PROJECT_CI_DEPLOY : enable install inside the build directory
#
# Once a tag is pushed, the release build will be packed and push to GitHub.
#

version: '{branch}-{build}'

clone_folder: C:\yall

skip_tags: true

branches:
  only:
    - master

environment:
    matrix:
        - image: Visual Studio 2015
          platform: x64
          generator: "Visual Studio 14 2015 Win64"
        - image: Visual Studio 2015
          platform: x64
          generator: "Visual Studio 12 2013 Win64"

before_build:
    - cd C:\yall
    - cmake -G"%generator%"
    - ps: if ( $env:APPVEYOR_PULL_REQUEST_NUMBER -eq '' ) { $env:APPVEYOR_REPO_TAG = $true }
    - ps: if ( $env:APPVEYOR_PULL_REQUEST_NUMBER -eq '' ) { $env:APPVEYOR_REPO_TAG_NAME = [IO.File]::ReadAllText("C:\yall\yall.version") }

build_script:
    - cmd: cmake --build . --config Release --target ALL_BUILD

after_build:
    - ps: if ( $env:APPVEYOR_REPO_TAG -eq $true ) { cmake --build . --config Release --target package }
    - ps: if ( $env:APPVEYOR_REPO_TAG -eq $true ) { cmake --build . --config Debug --target package }

test_script:
    - cmd: if "%generator%" NEQ "Visual Studio 12 2013 Win64" cmake --build . --target unit
    
artifacts:
    - path: 'yall-*.zip'
      name: yall_zip

deploy:
    release: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub
    artifact: yall_zip
    auth_token:
        secure: ZWCkNHmbrBurrU0WLBESAeFdNkhuUsae1TApe8LR/cakzx5Puw/akJZBC3uaISnw
    draft: false
    on:
        branch: master
