# Copyright (C) 2017 Quentin "Naccyde" Deslandes.
# Redistribution and use of this file is allowed according to the terms of the MIT license.
# For details see the LICENSE file distributed with yall.

#
# Appveyor configuration
#
# Build the project on Visual Studio 2015, in debug and release mode, 64 bits.
#
# CMake flags :
#   * PROJECT_CI_DEPLOY : enable install inside the build directory
#   * PROJECT_COVERAGE : works only on Linux, using gcov
#
# Once a tag is pushed, the release build will be packed and push to GitHub.
#

version: '{branch}-{build}'

skip_branch_with_pr: true
clone_folder: C:\yall

environment:
    matrix:
        - image: Visual Studio 2015
          platform: x64
          generator: "Visual Studio 14 2015 Win64"
        - image: Visual Studio 2015
          platform: x64
          generator: "Visual Studio 12 2013 Win64"

install:
  - cmd: choco install doxygen.portable

before_build:
    - cd c:\yall
    - cmake -G"%generator%"

build_script:
    - cmd: cmake --build . --config Debug --target ALL_BUILD
    - cmd: cmake --build . --config Debug --target package
    - cmd: cmake --build . --config Release --target ALL_BUILD
    - cmd: cmake --build . --config Release --target package

before_test:
    - cmd: if "%generator%" NEQ "Visual Studio 12 2013 Win64" cmake --build . --target yall_unit

test_script:
    - cmd: if "%generator%" NEQ "Visual Studio 12 2013 Win64" cmake --build . --target unit

artifacts:
    - path: 'out/packages/yall-*.zip'
      name: yall_pack

deploy:
    release: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub
    artifact: yall_pack
    auth_token:
        secure: TuQhBe4d+wcVLRETe+eopnipYx3swQuytr0a6nyKJMgAXg5L09P1CMFseftJTdmx
    draft: false
    force_update: true
    on:
        appveyor_repo_tag: true
