#
# Travis configuration file
#
# Used to setup proper build on Travis CI.
#
# CMake flags :
#   * BUILD_TYPE : Debug or Release
#   * PROJECT_CI_DEPLOY : enable install inside the build directory
#
# Install gcc-6 and lcov for coverage report. A recent version of CMake is also
# downloaded.
#
# Unit tests are run after each build. For the master and develop branches, the
# release build is analyzed through SonarQube.
#
# Each tag create a release on GitHub. Also, only commits on master should be
# tagged.
#

sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker pull naccyde/yall:latest
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export DEPLOY="true"; fi

script:
  - echo $TRAVIS_PULL_REQUEST
  - echo $DEPLOY
  - docker run -e "DEPLOY=$DEPLOY" -e "SONAR_KEY=$SONARCLOUD_API_KEY" -e "GITHUB_KEY=$GITHUB_PR_API_KEY" -e "GITHUB_PR=$TRAVIS_PULL_REQUEST" -v `pwd`:/yall --name yall naccyde/yall:latest

after_success:
  - docker cp yall:/build/packages ./
  - docker cp yall:/build/yall.version ./
  - export TRAVIS_TAG=`cat yall.version`

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: packages/*
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  on:
    tag: true
