dist: trusty
sudo: required
language: c

if: branch = master OR tag IS present OR branch = develop OR type = pull_request

addons:
  apt:
    packages:
    - python3-requests
    - python3-pip

services:
  - docker

install:
  # Docker
  - docker pull naccyde/yall
  - docker build --cache-from naccyde/yall -t naccyde/yall -f resources/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "naccyde" --password-stdin
  - docker push naccyde/yall
  # Pip, for release uploading script
  - pip3 install --user --upgrade requests

script:
  # Build
  - ./resources/ci.sh
  - if [ -n "$TRAVIS_TAG" ]; then bash python3 resources/artifacts.py -g $GITHUB_API_KEY -p $PACKAGECLOUD_API_KEY -t $TRAVIS_TAG --zip --linux; fi

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/out/public
  github_token: $GITHUB_API_KEY
  on:
    tags: true
