#
# Travis configuration file
#
# Used to setup proper build on Travis CI.
#
# CMake flags :
#   * BUILD_TYPE : Debug or Release
#   * PROJECT_CI_DEPLOY : enable install inside the build directory
#
# Install gcc-6 and lcov for coverage report. A recent version of CMake is also
# downloaded.
#
# Unit tests are run after each build. For the master and develop branches, the
# release build is analyzed through SonarQube.
#
# Each tag create a release on GitHub. Also, only commits on master should be
# tagged.
#

language: c

sudo: false
dist: trusty

# This will alow to build on master AND on pull requests
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: gcc-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:deadsnakes/ppa'
      - sourceline: 'ppa:adrozdoff/cmake'
    packages:
      - gcc-6
      - lcov
      - python3.5
      - valgrind
      - cmake
  sonarqube:
    token:
      secure: '$SONAR_API_KEY'
    branches:
      - master

cache:
  directories:
    - '$HOME/.sonar/cache'

install:
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
  - valgrind --version
  - python3 --version

before_script:
  - cmake -DCMAKE_BUILD_TYPE=Release -DYALL_VERSION_PATCH=${TRAVIS_BUILD_NUMBER} .

script:
  - make
  - make validate

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - resources/version.sh
  - if [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]; then TRAVIS_TAG=$(resources/version.sh); fi

# On release builds, in case of tag (only on master), the binaries will be deployed. To do this, we clean all that have been build, build Debug, install it and do the same for Release.
before_deploy:
  - cmake -DCMAKE_BUILD_TYPE=Release -DYALL_VERSION_PATCH=${TRAVIS_BUILD_NUMBER}
  - make package
  - cmake -DCMAKE_BUILD_TYPE=Debug -DYALL_VERSION_PATCH=${TRAVIS_BUILD_NUMBER}
  - make package

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: yall*.zip
  skip_cleanup: true
  on:
    tag: true
